### PR TITLE
Affinity only

### PR DESCRIPTION
**Pull request by mattragoza**
- bring affinity_only changes up to date with master
- support binary class-only, affinity-only, or both in train.py and combine_fold_results.py
- improve code readability

### CODE REVIEW

**Review by dkoes — CHANGES_REQUESTED** [review]
Why can't you determine the presence/absense of affinity from the model file rather than requiring a commandline option?

**Comment by mattragoza** [comment]
Do you mean in combine_fold_results.py? It doesn't know what the model file is, since it is only provided the outprefix. I suppose we could pass in the model file as another argument instead of the affinity flag.

**Comment by dkoes** [comment]
Can't it infer it from the output of train.py?

**Comment by mattragoza** [comment]
Yes, it could infer this based on whether it finds the *.auc.finaltest and *.rmsd.finaltest files.

**Pull request merged**
